// Local country + currency lists for trip onboarding. No network calls.
// currency is null when there is no single unambiguous currency — the user must pick one manually.
export type Country = { code: string; he: string; en: string; currency: string | null };

export const COUNTRIES: Country[] = [
  { code: "AF", he: "אפגניסטן", en: "Afghanistan", currency: "AFN" },
  { code: "AL", he: "אלבניה", en: "Albania", currency: "ALL" },
  { code: "DZ", he: "אלג'יריה", en: "Algeria", currency: "DZD" },
  { code: "AD", he: "אנדורה", en: "Andorra", currency: "EUR" },
  { code: "AO", he: "אנגולה", en: "Angola", currency: "AOA" },
  { code: "AG", he: "אנטיגואה וברבודה", en: "Antigua and Barbuda", currency: "XCD" },
  { code: "AR", he: "ארגנטינה", en: "Argentina", currency: "ARS" },
  { code: "AM", he: "ארמניה", en: "Armenia", currency: "AMD" },
  { code: "AU", he: "אוסטרליה", en: "Australia", currency: "AUD" },
  { code: "AT", he: "אוסטריה", en: "Austria", currency: "EUR" },
  { code: "AZ", he: "אזרבייג'ן", en: "Azerbaijan", currency: "AZN" },
  { code: "BS", he: "איי בהאמה", en: "Bahamas", currency: "BSD" },
  { code: "BH", he: "בחריין", en: "Bahrain", currency: "BHD" },
  { code: "BD", he: "בנגלדש", en: "Bangladesh", currency: "BDT" },
  { code: "BB", he: "ברבדוס", en: "Barbados", currency: "BBD" },
  { code: "BY", he: "בלארוס", en: "Belarus", currency: "BYN" },
  { code: "BE", he: "בלגיה", en: "Belgium", currency: "EUR" },
  { code: "BZ", he: "בליז", en: "Belize", currency: "BZD" },
  { code: "BJ", he: "בנין", en: "Benin", currency: "XOF" },
  { code: "BT", he: "בהוטן", en: "Bhutan", currency: "BTN" },
  { code: "BO", he: "בוליביה", en: "Bolivia", currency: "BOB" },
  { code: "BA", he: "בוסניה והרצגובינה", en: "Bosnia and Herzegovina", currency: "BAM" },
  { code: "BW", he: "בוצוואנה", en: "Botswana", currency: "BWP" },
  { code: "BR", he: "ברזיל", en: "Brazil", currency: "BRL" },
  { code: "BN", he: "ברוניי", en: "Brunei", currency: "BND" },
  { code: "BG", he: "בולגריה", en: "Bulgaria", currency: "BGN" },
  { code: "BF", he: "בורקינה פאסו", en: "Burkina Faso", currency: "XOF" },
  { code: "BI", he: "בורונדי", en: "Burundi", currency: "BIF" },
  { code: "CV", he: "כף ורדה", en: "Cape Verde", currency: "CVE" },
  { code: "KH", he: "קמבודיה", en: "Cambodia", currency: "KHR" },
  { code: "CM", he: "קמרון", en: "Cameroon", currency: "XAF" },
  { code: "CA", he: "קנדה", en: "Canada", currency: "CAD" },
  { code: "CF", he: "הרפובליקה המרכז-אפריקאית", en: "Central African Republic", currency: "XAF" },
  { code: "TD", he: "צ'אד", en: "Chad", currency: "XAF" },
  { code: "CL", he: "צ'ילה", en: "Chile", currency: "CLP" },
  { code: "CN", he: "סין", en: "China", currency: "CNY" },
  { code: "CO", he: "קולומביה", en: "Colombia", currency: "COP" },
  { code: "KM", he: "קומורו", en: "Comoros", currency: "KMF" },
  { code: "CG", he: "קונגו", en: "Congo", currency: "XAF" },
  { code: "CD", he: "קונגו (קינשאסה)", en: "Congo (DRC)", currency: "CDF" },
  { code: "CR", he: "קוסטה ריקה", en: "Costa Rica", currency: "CRC" },
  { code: "CI", he: "חוף השנהב", en: "Ivory Coast", currency: "XOF" },
  { code: "HR", he: "קרואטיה", en: "Croatia", currency: "EUR" },
  { code: "CU", he: "קובה", en: "Cuba", currency: "CUP" },
  { code: "CY", he: "קפריסין", en: "Cyprus", currency: "EUR" },
  { code: "CZ", he: "צ'כיה", en: "Czech Republic", currency: "CZK" },
  { code: "DK", he: "דנמרק", en: "Denmark", currency: "DKK" },
  { code: "DJ", he: "ג'יבוטי", en: "Djibouti", currency: "DJF" },
  { code: "DM", he: "דומיניקה", en: "Dominica", currency: "XCD" },
  { code: "DO", he: "הרפובליקה הדומיניקנית", en: "Dominican Republic", currency: "DOP" },
  { code: "EC", he: "אקוודור", en: "Ecuador", currency: "USD" },
  { code: "EG", he: "מצרים", en: "Egypt", currency: "EGP" },
  { code: "SV", he: "אל סלבדור", en: "El Salvador", currency: "USD" },
  { code: "GQ", he: "גינאה המשוונית", en: "Equatorial Guinea", currency: "XAF" },
  { code: "ER", he: "אריתריאה", en: "Eritrea", currency: "ERN" },
  { code: "EE", he: "אסטוניה", en: "Estonia", currency: "EUR" },
  { code: "SZ", he: "אסוואטיני", en: "Eswatini", currency: "SZL" },
  { code: "ET", he: "אתיופיה", en: "Ethiopia", currency: "ETB" },
  { code: "FJ", he: "פיג'י", en: "Fiji", currency: "FJD" },
  { code: "FI", he: "פינלנד", en: "Finland", currency: "EUR" },
  { code: "FR", he: "צרפת", en: "France", currency: "EUR" },
  { code: "GA", he: "גבון", en: "Gabon", currency: "XAF" },
  { code: "GM", he: "גמביה", en: "Gambia", currency: "GMD" },
  { code: "GE", he: "גאורגיה", en: "Georgia", currency: "GEL" },
  { code: "DE", he: "גרמניה", en: "Germany", currency: "EUR" },
  { code: "GH", he: "גאנה", en: "Ghana", currency: "GHS" },
  { code: "GR", he: "יוון", en: "Greece", currency: "EUR" },
  { code: "GD", he: "גרנדה", en: "Grenada", currency: "XCD" },
  { code: "GT", he: "גואטמלה", en: "Guatemala", currency: "GTQ" },
  { code: "GN", he: "גינאה", en: "Guinea", currency: "GNF" },
  { code: "GW", he: "גינאה-ביסאו", en: "Guinea-Bissau", currency: "XOF" },
  { code: "GY", he: "גיאנה", en: "Guyana", currency: "GYD" },
  { code: "HT", he: "האיטי", en: "Haiti", currency: "HTG" },
  { code: "HN", he: "הונדורס", en: "Honduras", currency: "HNL" },
  { code: "HU", he: "הונגריה", en: "Hungary", currency: "HUF" },
  { code: "IS", he: "איסלנד", en: "Iceland", currency: "ISK" },
  { code: "IN", he: "הודו", en: "India", currency: "INR" },
  { code: "ID", he: "אינדונזיה", en: "Indonesia", currency: "IDR" },
  { code: "IR", he: "איראן", en: "Iran", currency: "IRR" },
  { code: "IQ", he: "עיראק", en: "Iraq", currency: "IQD" },
  { code: "IE", he: "אירלנד", en: "Ireland", currency: "EUR" },
  { code: "IL", he: "ישראל", en: "Israel", currency: "ILS" },
  { code: "IT", he: "איטליה", en: "Italy", currency: "EUR" },
  { code: "JM", he: "ג'מייקה", en: "Jamaica", currency: "JMD" },
  { code: "JP", he: "יפן", en: "Japan", currency: "JPY" },
  { code: "JO", he: "ירדן", en: "Jordan", currency: "JOD" },
  { code: "KZ", he: "קזחסטן", en: "Kazakhstan", currency: "KZT" },
  { code: "KE", he: "קניה", en: "Kenya", currency: "KES" },
  { code: "KI", he: "קיריבטי", en: "Kiribati", currency: "AUD" },
  { code: "KW", he: "כווית", en: "Kuwait", currency: "KWD" },
  { code: "KG", he: "קירגיזסטן", en: "Kyrgyzstan", currency: "KGS" },
  { code: "LA", he: "לאוס", en: "Laos", currency: "LAK" },
  { code: "LV", he: "לטביה", en: "Latvia", currency: "EUR" },
  { code: "LB", he: "לבנון", en: "Lebanon", currency: "LBP" },
  { code: "LS", he: "לסוטו", en: "Lesotho", currency: "LSL" },
  { code: "LR", he: "ליבריה", en: "Liberia", currency: "LRD" },
  { code: "LY", he: "לוב", en: "Libya", currency: "LYD" },
  { code: "LI", he: "ליכטנשטיין", en: "Liechtenstein", currency: "CHF" },
  { code: "LT", he: "ליטא", en: "Lithuania", currency: "EUR" },
  { code: "LU", he: "לוקסמבורג", en: "Luxembourg", currency: "EUR" },
  { code: "MG", he: "מדגסקר", en: "Madagascar", currency: "MGA" },
  { code: "MW", he: "מלאווי", en: "Malawi", currency: "MWK" },
  { code: "MY", he: "מלזיה", en: "Malaysia", currency: "MYR" },
  { code: "MV", he: "האיים המלדיביים", en: "Maldives", currency: "MVR" },
  { code: "ML", he: "מאלי", en: "Mali", currency: "XOF" },
  { code: "MT", he: "מלטה", en: "Malta", currency: "EUR" },
  { code: "MH", he: "איי מרשל", en: "Marshall Islands", currency: "USD" },
  { code: "MR", he: "מאוריטניה", en: "Mauritania", currency: "MRU" },
  { code: "MU", he: "מאוריציוס", en: "Mauritius", currency: "MUR" },
  { code: "MX", he: "מקסיקו", en: "Mexico", currency: "MXN" },
  { code: "FM", he: "מיקרונזיה", en: "Micronesia", currency: "USD" },
  { code: "MD", he: "מולדובה", en: "Moldova", currency: "MDL" },
  { code: "MC", he: "מונקו", en: "Monaco", currency: "EUR" },
  { code: "MN", he: "מונגוליה", en: "Mongolia", currency: "MNT" },
  { code: "ME", he: "מונטנגרו", en: "Montenegro", currency: "EUR" },
  { code: "MA", he: "מרוקו", en: "Morocco", currency: "MAD" },
  { code: "MZ", he: "מוזמביק", en: "Mozambique", currency: "MZN" },
  { code: "MM", he: "מיאנמר", en: "Myanmar", currency: "MMK" },
  { code: "NA", he: "נמיביה", en: "Namibia", currency: "NAD" },
  { code: "NR", he: "נאורו", en: "Nauru", currency: "AUD" },
  { code: "NP", he: "נפאל", en: "Nepal", currency: "NPR" },
  { code: "NL", he: "הולנד", en: "Netherlands", currency: "EUR" },
  { code: "NZ", he: "ניו זילנד", en: "New Zealand", currency: "NZD" },
  { code: "NI", he: "ניקרגואה", en: "Nicaragua", currency: "NIO" },
  { code: "NE", he: "ניז'ר", en: "Niger", currency: "XOF" },
  { code: "NG", he: "ניגריה", en: "Nigeria", currency: "NGN" },
  { code: "KP", he: "צפון קוריאה", en: "North Korea", currency: "KPW" },
  { code: "MK", he: "צפון מקדוניה", en: "North Macedonia", currency: "MKD" },
  { code: "NO", he: "נורווגיה", en: "Norway", currency: "NOK" },
  { code: "OM", he: "עומאן", en: "Oman", currency: "OMR" },
  { code: "PK", he: "פקיסטן", en: "Pakistan", currency: "PKR" },
  { code: "PW", he: "פלאו", en: "Palau", currency: "USD" },
  { code: "PS", he: "פלסטין", en: "Palestine", currency: "ILS" },
  { code: "PA", he: "פנמה", en: "Panama", currency: "USD" },
  { code: "PG", he: "פפואה גינאה החדשה", en: "Papua New Guinea", currency: "PGK" },
  { code: "PY", he: "פרגוואי", en: "Paraguay", currency: "PYG" },
  { code: "PE", he: "פרו", en: "Peru", currency: "PEN" },
  { code: "PH", he: "הפיליפינים", en: "Philippines", currency: "PHP" },
  { code: "PL", he: "פולין", en: "Poland", currency: "PLN" },
  { code: "PT", he: "פורטוגל", en: "Portugal", currency: "EUR" },
  { code: "QA", he: "קטאר", en: "Qatar", currency: "QAR" },
  { code: "RO", he: "רומניה", en: "Romania", currency: "RON" },
  { code: "RU", he: "רוסיה", en: "Russia", currency: "RUB" },
  { code: "RW", he: "רואנדה", en: "Rwanda", currency: "RWF" },
  { code: "KN", he: "סנט קיטס ונוויס", en: "Saint Kitts and Nevis", currency: "XCD" },
  { code: "LC", he: "סנט לוסיה", en: "Saint Lucia", currency: "XCD" },
  { code: "VC", he: "סנט וינסנט והגרנדינים", en: "Saint Vincent and the Grenadines", currency: "XCD" },
  { code: "WS", he: "סמואה", en: "Samoa", currency: "WST" },
  { code: "SM", he: "סן מרינו", en: "San Marino", currency: "EUR" },
  { code: "ST", he: "סאו טומה ופרינסיפה", en: "Sao Tome and Principe", currency: "STN" },
  { code: "SA", he: "ערב הסעודית", en: "Saudi Arabia", currency: "SAR" },
  { code: "SN", he: "סנגל", en: "Senegal", currency: "XOF" },
  { code: "RS", he: "סרביה", en: "Serbia", currency: "RSD" },
  { code: "SC", he: "סיישל", en: "Seychelles", currency: "SCR" },
  { code: "SL", he: "סיירה לאון", en: "Sierra Leone", currency: "SLE" },
  { code: "SG", he: "סינגפור", en: "Singapore", currency: "SGD" },
  { code: "SK", he: "סלובקיה", en: "Slovakia", currency: "EUR" },
  { code: "SI", he: "סלובניה", en: "Slovenia", currency: "EUR" },
  { code: "SB", he: "איי שלמה", en: "Solomon Islands", currency: "SBD" },
  { code: "SO", he: "סומליה", en: "Somalia", currency: "SOS" },
  { code: "ZA", he: "דרום אפריקה", en: "South Africa", currency: "ZAR" },
  { code: "KR", he: "דרום קוריאה", en: "South Korea", currency: "KRW" },
  { code: "SS", he: "דרום סודן", en: "South Sudan", currency: "SSP" },
  { code: "ES", he: "ספרד", en: "Spain", currency: "EUR" },
  { code: "LK", he: "סרי לנקה", en: "Sri Lanka", currency: "LKR" },
  { code: "SD", he: "סודן", en: "Sudan", currency: "SDG" },
  { code: "SR", he: "סורינאם", en: "Suriname", currency: "SRD" },
  { code: "SE", he: "שוודיה", en: "Sweden", currency: "SEK" },
  { code: "CH", he: "שווייץ", en: "Switzerland", currency: "CHF" },
  { code: "SY", he: "סוריה", en: "Syria", currency: "SYP" },
  { code: "TW", he: "טייוואן", en: "Taiwan", currency: "TWD" },
  { code: "TJ", he: "טג'יקיסטן", en: "Tajikistan", currency: "TJS" },
  { code: "TZ", he: "טנזניה", en: "Tanzania", currency: "TZS" },
  { code: "TH", he: "תאילנד", en: "Thailand", currency: "THB" },
  { code: "TL", he: "מזרח טימור", en: "Timor-Leste", currency: "USD" },
  { code: "TG", he: "טוגו", en: "Togo", currency: "XOF" },
  { code: "TO", he: "טונגה", en: "Tonga", currency: "TOP" },
  { code: "TT", he: "טרינידד וטובגו", en: "Trinidad and Tobago", currency: "TTD" },
  { code: "TN", he: "תוניסיה", en: "Tunisia", currency: "TND" },
  { code: "TR", he: "טורקיה", en: "Turkey", currency: "TRY" },
  { code: "TM", he: "טורקמניסטן", en: "Turkmenistan", currency: "TMT" },
  { code: "TV", he: "טובאלו", en: "Tuvalu", currency: "AUD" },
  { code: "UG", he: "אוגנדה", en: "Uganda", currency: "UGX" },
  { code: "UA", he: "אוקראינה", en: "Ukraine", currency: "UAH" },
  { code: "AE", he: "איחוד האמירויות", en: "United Arab Emirates", currency: "AED" },
  { code: "GB", he: "בריטניה", en: "United Kingdom", currency: "GBP" },
  { code: "US", he: "ארצות הברית", en: "United States", currency: "USD" },
  { code: "UY", he: "אורוגוואי", en: "Uruguay", currency: "UYU" },
  { code: "UZ", he: "אוזבקיסטן", en: "Uzbekistan", currency: "UZS" },
  { code: "VU", he: "ונואטו", en: "Vanuatu", currency: "VUV" },
  { code: "VA", he: "הוותיקן", en: "Vatican City", currency: "EUR" },
  { code: "VE", he: "ונצואלה", en: "Venezuela", currency: "VES" },
  { code: "VN", he: "וייטנאם", en: "Vietnam", currency: "VND" },
  { code: "YE", he: "תימן", en: "Yemen", currency: "YER" },
  { code: "ZM", he: "זמביה", en: "Zambia", currency: "ZMW" },
  { code: "ZW", he: "זימבבואה", en: "Zimbabwe", currency: null },
  // Common territories
  { code: "HK", he: "הונג קונג", en: "Hong Kong", currency: "HKD" },
  { code: "MO", he: "מקאו", en: "Macau", currency: "MOP" },
  { code: "PR", he: "פוארטו ריקו", en: "Puerto Rico", currency: "USD" },
  { code: "GU", he: "גואם", en: "Guam", currency: "USD" },
  { code: "VI", he: "איי הבתולה", en: "U.S. Virgin Islands", currency: "USD" },
  { code: "AW", he: "ארובה", en: "Aruba", currency: "AWG" },
  { code: "CW", he: "קוראסאו", en: "Curacao", currency: "ANG" },
  { code: "BM", he: "ברמודה", en: "Bermuda", currency: "BMD" },
  { code: "KY", he: "איי קיימן", en: "Cayman Islands", currency: "KYD" },
  { code: "TC", he: "איי טרקס וקייקוס", en: "Turks and Caicos Islands", currency: "USD" },
  { code: "GP", he: "גוואדלופ", en: "Guadeloupe", currency: "EUR" },
  { code: "MQ", he: "מרטיניק", en: "Martinique", currency: "EUR" },
  { code: "RE", he: "ראוניון", en: "Reunion", currency: "EUR" },
  { code: "GF", he: "גיאנה הצרפתית", en: "French Guiana", currency: "EUR" },
  { code: "PF", he: "פולינזיה הצרפתית", en: "French Polynesia", currency: "XPF" },
  { code: "NC", he: "קלדוניה החדשה", en: "New Caledonia", currency: "XPF" },
  { code: "GL", he: "גרינלנד", en: "Greenland", currency: "DKK" },
  { code: "FO", he: "איי פארו", en: "Faroe Islands", currency: "DKK" },
  { code: "GI", he: "גיברלטר", en: "Gibraltar", currency: "GIP" },
  { code: "IM", he: "האי מאן", en: "Isle of Man", currency: "GBP" },
  { code: "JE", he: "ג'רזי", en: "Jersey", currency: "GBP" },
  { code: "GG", he: "גרנזי", en: "Guernsey", currency: "GBP" },
  { code: "AX", he: "איי אולנד", en: "Aland Islands", currency: "EUR" },
  { code: "XK", he: "קוסובו", en: "Kosovo", currency: "EUR" },
  { code: "CK", he: "איי קוק", en: "Cook Islands", currency: "NZD" },
  { code: "AS", he: "סמואה האמריקנית", en: "American Samoa", currency: "USD" },
  { code: "MP", he: "איי מריאנה הצפוניים", en: "Northern Mariana Islands", currency: "USD" },
  { code: "FK", he: "איי פוקלנד", en: "Falkland Islands", currency: "FKP" },
  { code: "SH", he: "סנט הלנה", en: "Saint Helena", currency: "SHP" },
  { code: "AI", he: "אנגווילה", en: "Anguilla", currency: "XCD" },
  { code: "MS", he: "מונטסראט", en: "Montserrat", currency: "XCD" },
  { code: "VG", he: "איי הבתולה הבריטיים", en: "British Virgin Islands", currency: "USD" },
  { code: "SX", he: "סן מרטן", en: "Sint Maarten", currency: "ANG" },
  { code: "BQ", he: "בונייר", en: "Bonaire", currency: "USD" },
  { code: "PM", he: "סן פייר ומיקלון", en: "Saint Pierre and Miquelon", currency: "EUR" },
  { code: "WF", he: "ווליס ופוטונה", en: "Wallis and Futuna", currency: "XPF" },
  { code: "NF", he: "האי נורפוק", en: "Norfolk Island", currency: "AUD" },
  { code: "NU", he: "ניואה", en: "Niue", currency: "NZD" },
  { code: "TK", he: "טוקלאו", en: "Tokelau", currency: "NZD" },
  { code: "IO", he: "הטריטוריה הבריטית באוקיינוס ההודי", en: "British Indian Ocean Territory", currency: "USD" },
  { code: "PN", he: "איי פיטקרן", en: "Pitcairn Islands", currency: "NZD" },
  { code: "GS", he: "ג'ורג'יה הדרומית", en: "South Georgia", currency: "GBP" },
  { code: "SJ", he: "סבאלברד", en: "Svalbard", currency: "NOK" },
  { code: "AQ", he: "אנטארקטיקה", en: "Antarctica", currency: null },
  { code: "EH", he: "סהרה המערבית", en: "Western Sahara", currency: "MAD" },
];

export const CURRENCIES: string[] = Array.from(
  new Set(["ILS", "USD", "EUR", "GBP", ...COUNTRIES.map((c) => c.currency).filter((c): c is string => c !== null)]),
).sort();

export function isValidCurrency(code: string): boolean {
  return CURRENCIES.includes(code.toUpperCase());
}

export function searchCountries(q: string): Country[] {
  const s = q.trim().toLowerCase();
  if (!s) return COUNTRIES;
  return COUNTRIES.filter((c) => c.he.includes(s) || c.en.toLowerCase().includes(s) || c.code.toLowerCase() === s);
}
