/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RecommendationsRouteImport } from './routes/recommendations'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as ItineraryRouteImport } from './routes/itinerary'
import { Route as BudgetRouteImport } from './routes/budget'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ItineraryIndexRouteImport } from './routes/itinerary.index'
import { Route as JoinTokenRouteImport } from './routes/join.$token'
import { Route as ItineraryDayIdRouteImport } from './routes/itinerary.$dayId'

const RecommendationsRoute = RecommendationsRouteImport.update({
  id: '/recommendations',
  path: '/recommendations',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ItineraryRoute = ItineraryRouteImport.update({
  id: '/itinerary',
  path: '/itinerary',
  getParentRoute: () => rootRouteImport,
} as any)
const BudgetRoute = BudgetRouteImport.update({
  id: '/budget',
  path: '/budget',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ItineraryIndexRoute = ItineraryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ItineraryRoute,
} as any)
const JoinTokenRoute = JoinTokenRouteImport.update({
  id: '/join/$token',
  path: '/join/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ItineraryDayIdRoute = ItineraryDayIdRouteImport.update({
  id: '/$dayId',
  path: '/$dayId',
  getParentRoute: () => ItineraryRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/budget': typeof BudgetRoute
  '/itinerary': typeof ItineraryRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/recommendations': typeof RecommendationsRoute
  '/itinerary/$dayId': typeof ItineraryDayIdRoute
  '/join/$token': typeof JoinTokenRoute
  '/itinerary/': typeof ItineraryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/budget': typeof BudgetRoute
  '/onboarding': typeof OnboardingRoute
  '/recommendations': typeof RecommendationsRoute
  '/itinerary/$dayId': typeof ItineraryDayIdRoute
  '/join/$token': typeof JoinTokenRoute
  '/itinerary': typeof ItineraryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/budget': typeof BudgetRoute
  '/itinerary': typeof ItineraryRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/recommendations': typeof RecommendationsRoute
  '/itinerary/$dayId': typeof ItineraryDayIdRoute
  '/join/$token': typeof JoinTokenRoute
  '/itinerary/': typeof ItineraryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/budget'
    | '/itinerary'
    | '/onboarding'
    | '/recommendations'
    | '/itinerary/$dayId'
    | '/join/$token'
    | '/itinerary/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/budget'
    | '/onboarding'
    | '/recommendations'
    | '/itinerary/$dayId'
    | '/join/$token'
    | '/itinerary'
  id:
    | '__root__'
    | '/'
    | '/budget'
    | '/itinerary'
    | '/onboarding'
    | '/recommendations'
    | '/itinerary/$dayId'
    | '/join/$token'
    | '/itinerary/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BudgetRoute: typeof BudgetRoute
  ItineraryRoute: typeof ItineraryRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
  RecommendationsRoute: typeof RecommendationsRoute
  JoinTokenRoute: typeof JoinTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/recommendations': {
      id: '/recommendations'
      path: '/recommendations'
      fullPath: '/recommendations'
      preLoaderRoute: typeof RecommendationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/itinerary': {
      id: '/itinerary'
      path: '/itinerary'
      fullPath: '/itinerary'
      preLoaderRoute: typeof ItineraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/budget': {
      id: '/budget'
      path: '/budget'
      fullPath: '/budget'
      preLoaderRoute: typeof BudgetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/itinerary/': {
      id: '/itinerary/'
      path: '/'
      fullPath: '/itinerary/'
      preLoaderRoute: typeof ItineraryIndexRouteImport
      parentRoute: typeof ItineraryRoute
    }
    '/join/$token': {
      id: '/join/$token'
      path: '/join/$token'
      fullPath: '/join/$token'
      preLoaderRoute: typeof JoinTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/itinerary/$dayId': {
      id: '/itinerary/$dayId'
      path: '/$dayId'
      fullPath: '/itinerary/$dayId'
      preLoaderRoute: typeof ItineraryDayIdRouteImport
      parentRoute: typeof ItineraryRoute
    }
  }
}

interface ItineraryRouteChildren {
  ItineraryDayIdRoute: typeof ItineraryDayIdRoute
  ItineraryIndexRoute: typeof ItineraryIndexRoute
}

const ItineraryRouteChildren: ItineraryRouteChildren = {
  ItineraryDayIdRoute: ItineraryDayIdRoute,
  ItineraryIndexRoute: ItineraryIndexRoute,
}

const ItineraryRouteWithChildren = ItineraryRoute._addFileChildren(
  ItineraryRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BudgetRoute: BudgetRoute,
  ItineraryRoute: ItineraryRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
  RecommendationsRoute: RecommendationsRoute,
  JoinTokenRoute: JoinTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
